/**
 * This file was generated. Do NOT edit this file.
 */

import fetch from 'node-fetch'
import { type ZodRawShape, z } from 'zod'
import { commons_WorkbookIdSchema } from '../schemas.js'
import type { Tool } from './index.js'

const params = {
  workbookId: commons_WorkbookIdSchema.describe('ID of workbook'),
  completed: z
    .boolean()
    .optional()
    .describe(
      'If true, only return commits that have been completed. If false, only return commits that have not been completed. If not provided, return all commits.',
    ),
} as ZodRawShape

export const getWorkbookCommits: Tool<typeof params> = {
  name: 'getWorkbookCommits',
  description: 'Get commits for a workbook: Returns the commits for a workbook',
  params,
  cb: async ({ workbookId, completed }) => {
    try {
      const searchParams = { completed }

      const searchParamsString = new URLSearchParams(JSON.parse(JSON.stringify(searchParams))).toString()
      const baseUrl = process.env.FLATFILE_API_URL || 'https://platform.flatfile.com/api/v1'
      const url = `${baseUrl}/workbooks/${workbookId}/commits${searchParamsString ? `?${searchParamsString}` : ''}`

      const response = await fetch(url, {
        method: 'GET',
        headers: {
          'X-Disable-Hooks': 'true',
          Authorization: `Bearer ${process.env.FLATFILE_BEARER_TOKEN}`,
          'Content-Type': 'application/json',
        },
      })

      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status} - ${response.statusText}`)
      }

      const data = (await response.json()) as { data: unknown }

      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify(data.data, null, 2),
          },
        ],
        status: 'success',
      }
    } catch (error) {
      return {
        content: [{ type: 'text', text: `Error: ${error}` }],
        status: 'failed',
      }
    }
  },
}
