/**
 * This file was generated. Do NOT edit this file.
 */

import fetch from 'node-fetch'
import { type ZodRawShape, z } from 'zod'
import { commons_SpaceIdSchema } from '../schemas.js'
import type { Tool } from './index.js'

const params = {
  scope: z.string().optional().describe('The resource ID of the event stream (space or environment id)'),
  spaceId: commons_SpaceIdSchema.optional().describe('The space ID of the event stream'),
} as ZodRawShape

export const getEventTokenEvents: Tool<typeof params> = {
  name: 'getEventTokenEvents',
  description: 'Get subscription credentials: Get a token which can be used to subscribe to events for this space',
  params,
  cb: async ({ scope, spaceId }) => {
    try {
      const searchParams = { scope, spaceId }

      const searchParamsString = new URLSearchParams(JSON.parse(JSON.stringify(searchParams))).toString()
      const baseUrl = process.env.FLATFILE_API_URL || 'https://platform.flatfile.com/api/v1'
      const url = `${baseUrl}/subscription${searchParamsString ? `?${searchParamsString}` : ''}`

      const response = await fetch(url, {
        method: 'GET',
        headers: {
          'X-Disable-Hooks': 'true',
          Authorization: `Bearer ${process.env.FLATFILE_BEARER_TOKEN}`,
          'Content-Type': 'application/json',
        },
      })

      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status} - ${response.statusText}`)
      }

      const data = (await response.json()) as { data: unknown }

      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify(data.data, null, 2),
          },
        ],
        status: 'success',
      }
    } catch (error) {
      return {
        content: [{ type: 'text', text: `Error: ${error}` }],
        status: 'failed',
      }
    }
  },
}
