/**
 * This file was generated. Do NOT edit this file.
 */

import fetch from 'node-fetch'
import { type ZodRawShape, z } from 'zod'
import { commons_ActorIdUnionSchema, commons_EnvironmentIdSchema, commons_SpaceIdSchema } from '../schemas.js'
import type { Tool } from './index.js'

const params = {
  environmentId: commons_EnvironmentIdSchema.optional().describe('The Environment of the secret.'),
  spaceId: commons_SpaceIdSchema.optional().describe('The Space of the secret.'),
  actorId: commons_ActorIdUnionSchema.optional().describe('The Actor of the secret.'),
} as ZodRawShape

export const listSecrets: Tool<typeof params> = {
  name: 'listSecrets',
  description: 'List secrets: Fetch all secrets for a given environmentId and optionally apply space overrides',
  params,
  cb: async ({ environmentId, spaceId, actorId }) => {
    try {
      const searchParams = { environmentId, spaceId, actorId }

      const searchParamsString = new URLSearchParams(JSON.parse(JSON.stringify(searchParams))).toString()
      const baseUrl = process.env.FLATFILE_API_URL || 'https://platform.flatfile.com/api/v1'
      const url = `${baseUrl}/secrets${searchParamsString ? `?${searchParamsString}` : ''}`

      const response = await fetch(url, {
        method: 'GET',
        headers: {
          'X-Disable-Hooks': 'true',
          Authorization: `Bearer ${process.env.FLATFILE_BEARER_TOKEN}`,
          'Content-Type': 'application/json',
        },
      })

      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status} - ${response.statusText}`)
      }

      const data = (await response.json()) as { data: unknown }

      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify(data.data, null, 2),
          },
        ],
        status: 'success',
      }
    } catch (error) {
      return {
        content: [{ type: 'text', text: `Error: ${error}` }],
        status: 'failed',
      }
    }
  },
}
