/**
 * This file was generated. Do NOT edit this file.
 */

import fetch from 'node-fetch'
import { type ZodRawShape, z } from 'zod'
import { commons_DocumentIdSchema, commons_SpaceIdSchema, documents_DocumentConfigSchema } from '../schemas.js'
import type { Tool } from './index.js'

const params = {
  spaceId: commons_SpaceIdSchema.describe('ID of space to return'),
  documentId: commons_DocumentIdSchema.describe('ID of document to return'),
  body: documents_DocumentConfigSchema,
} as ZodRawShape

export const updateDocument: Tool<typeof params> = {
  name: 'updateDocument',
  description: 'Update a document: updates a single document, for only the body and title',
  params,
  cb: async ({ spaceId, documentId, body }) => {
    try {
      const searchParams = {}

      const searchParamsString = new URLSearchParams(JSON.parse(JSON.stringify(searchParams))).toString()
      const baseUrl = process.env.FLATFILE_API_URL || 'https://platform.flatfile.com/api/v1'
      const url = `${baseUrl}/spaces/${spaceId}/documents/${documentId}${searchParamsString ? `?${searchParamsString}` : ''}`

      const response = await fetch(url, {
        method: 'PATCH',
        headers: {
          'X-Disable-Hooks': 'true',
          Authorization: `Bearer ${process.env.FLATFILE_BEARER_TOKEN}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      })

      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status} - ${response.statusText}`)
      }

      const data = (await response.json()) as { data: unknown }

      return {
        content: [
          {
            type: 'text',
            text: JSON.stringify(data.data, null, 2),
          },
        ],
        status: 'success',
      }
    } catch (error) {
      return {
        content: [{ type: 'text', text: `Error: ${error}` }],
        status: 'failed',
      }
    }
  },
}
